# Generated by Django 5.1 on 2024-08-21 02:55

import app.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movies",
            fields=[
                ("movie_no", models.IntegerField(primary_key=True, serialize=False)),
                ("movie_name", models.CharField(max_length=50)),
                ("movie_type", models.CharField(max_length=50)),
                ("release_date", models.DateField()),
                ("quality", models.CharField(max_length=10)),
                ("movie_size", models.CharField(max_length=50)),
                ("profile", models.ImageField(upload_to="")),
                (
                    "lang",
                    models.CharField(
                        choices=[("Engish", "English"), ("Hindi", "Hindi")],
                        max_length=50,
                    ),
                ),
                (
                    "movie",
                    models.FileField(
                        null=True,
                        upload_to="video/%y",
                        validators=[app.validator.file_size],
                    ),
                ),
            ],
        ),
    ]
